### Create student
POST http://localhost:8080/school/api/students
Content-Type: application/json

{
"firstName": "John",
  "lastName": "Doe",
  "age": 33
}


### Get all students
GET http://localhost:8080/school/api/students
Accept: application/json


### Get student(s), who name include namePart
GET http://localhost:8080/school/api/students?namePart=cap
Accept: application/json


### Get student(s) with age 33
GET http://localhost:8080/school/api/students?age=33
Accept: application/json


### Get student(s), who name include namePart AND with age 44
GET http://localhost:8080/school/api/students?namePart=cap&age=44
Accept: application/json


### Update student first name
PUT http://localhost:8080/school/api/students/1
Content-Type: application/json

{
  "firstName": "Pokalakki"
}